### PR TITLE
Add optional Hunter support to provide dependencies

### PR DESCRIPTION
**Pull request by NeroBurner**
Use https://github.com/cpp-pm/hunter as optional pure CMake dependency manager. To wake up Hunter and tell it to provide the dependencies for your project just add `-DHUNTER_ENABLED=ON` to your cmake configuration line

### CODE REVIEW

**Comment by Xeverous** [comment]
Sorry, but I don't really like it. You commit a lot of boilerplate and (probably intrusively) modify the current CMake recipe. I have very little knowledge of what Hunter actually is, but IMO any package manager should not need to introduce that much code to enable working with a library.

The library in it's current form can already be used simply by cloning the repository and using `add_subdirectory`.

**Comment by NeroBurner** [comment]
now less intrusive, less boilerplate, just a single file added by [CMAKE_PROJECT_INCLUDE_BEFORE](https://cmake.org/cmake/help/v3.15/variable/CMAKE_FIND_PACKAGE_PREFER_CONFIG.html).

Configure your project using CMAKE_PROJECT_INCLUDE_BEFORE and Hunter will provide nlohmann_json and Boost headers for the project to find.
    
```sh
cmake -DCMAKE_PROJECT_INCLUDE_BEFORE=[%cd%|$PWD]/SetupHunter.cmake -S . -B build
```


Note: This is a CMake 3.15 feature. So to use Hunter in this way CMake 3.15 is needed

see: https://cmake.org/cmake/help/v3.15/variable/CMAKE_FIND_PACKAGE_PREFER_CONFIG.html

**Comment by Xeverous** [comment]
Ok, this looks much better now. Does hunter support optional usage of itself? I want the library to be usable without hunter too.

**Comment by NeroBurner** [comment]
Yes both of my proposals were optional. In both cases the project can be configured like Hunter isn't even there (default)

On May 2, 2020 9:43:17 AM GMT+02:00, Xeverous <notifications@github.com> wrote:
>Ok, this looks much better now. Does hunter support optional usage of
>itself? I want the library to be usable without hunter too.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Xeverous/fuser/pull/1#issuecomment-622810120

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
